export enum RegisterNames {
    INPUT_STREAM = 0,
    INPUT_POINTER = 1,

    OUTPUT_STREAM = 2,
    OUTPUT_POINTER = 3,
    
    CURRENT_TOKEN_STREAM = 4,
    
    PRINTER_STREAM = 5,
    PRINTER_POINTER = 6,
    
    EXECUTOR_STREAM = 7,
    EXECUTOR_POINTER = 8,
    
    COMMAND_STACK = 9,
    ARGUMENTS_STACK = 10,
    ARGUMENTS_STREAM = 11,
    EXECUTION_RESULT = 12
}